version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    ports:
      - "8085:9091"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:bookworm
    container_name: crm-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=tech-talk-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tech-talk-db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db: {}